### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by conformist1** [xnamahx/APC40_MkIIx#8]
See code from log below:

2020-10-13T16:42:29.688727: info: RemoteScriptError: Traceback (most recent call last):

2020-10-13T16:42:29.688760: info: RemoteScriptError:   File "<string>", line 1, in <module>

2020-10-13T16:42:29.688850: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC40/__init__.py", line 16, in <module>

2020-10-13T16:42:29.688923: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC40/APC40.py", line 28, in <module>

2020-10-13T16:42:29.688991: info: RemoteScriptError: ImportError
2020-10-13T16:42:29.689005: info: RemoteScriptError: : 
2020-10-13T16:42:29.689017: info: RemoteScriptError: cannot import name make_biled_skin
2020-10-13T16:42:29.689045: info: RemoteScriptError: 

2020-10-13T16:42:29.718972: info: RemoteScriptError: Traceback (most recent call last):

2020-10-13T16:42:29.719009: info: RemoteScriptError:   File "<string>", line 1, in <module>

2020-10-13T16:42:29.719214: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC40_MkII/__init__.py", line 17, in <module>

2020-10-13T16:42:29.719308: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC40_MkII/APC40_MkII.py", line 34, in <module>

2020-10-13T16:42:29.719381: info: RemoteScriptError: ImportError
2020-10-13T16:42:29.719396: info: RemoteScriptError: : 
2020-10-13T16:42:29.719409: info: RemoteScriptError: cannot import name make_rgb_skin
2020-10-13T16:42:29.719421: info: RemoteScriptError: 

2020-10-13T16:42:29.840726: info: RemoteScriptError: Traceback (most recent call last):

2020-10-13T16:42:29.840768: info: RemoteScriptError:   File "<string>", line 1, in <module>

2020-10-13T16:42:29.840905: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC_Key_25/__init__.py", line 16, in <module>

2020-10-13T16:42:29.841019: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC_Key_25/APC_Key_25.py", line 20, in <module>

2020-10-13T16:42:29.841128: info: RemoteScriptError: ImportError
2020-10-13T16:42:29.841151: info: RemoteScriptError: : 
2020-10-13T16:42:29.841171: info: RemoteScriptError: cannot import name make_biled_skin
2020-10-13T16:42:29.841191: info: RemoteScriptError: 

2020-10-13T16:42:29.955560: info: RemoteScriptError: Traceback (most recent call last):

2020-10-13T16:42:29.955603: info: RemoteScriptError:   File "<string>", line 1, in <module>

2020-10-13T16:42:29.955738: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC_mini/__init__.py", line 16, in <module>

2020-10-13T16:42:29.955855: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC_mini/APC_mini.py", line 7, in <module>

2020-10-13T16:42:29.955969: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC_Key_25/__init__.py", line 16, in <module>

2020-10-13T16:42:29.956080: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC_Key_25/APC_Key_25.py", line 20, in <module>

2020-10-13T16:42:29.956235: info: RemoteScriptError: ImportError
2020-10-13T16:42:29.956270: info: RemoteScriptError: : 
2020-10-13T16:42:29.956292: info: RemoteScriptError: cannot import name make_biled_skin
2020-10-13T16:42:29.956310: info: RemoteScriptError: 

2020-10-13T16:42:29.997653: info: RemoteScriptError: Traceback (most recent call last):

2020-10-13T16:42:29.997682: info: RemoteScriptError:   File "<string>", line 1, in <module>

2020-10-13T16:42:29.997768: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC20/__init__.py", line 16, in <module>

2020-10-13T16:42:29.997837: info: RemoteScriptError:   File "/Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/APC20/APC20.py", line 21, in <module>

2020-10-13T16:42:29.997904: info: RemoteScriptError: ImportError
2020-10-13T16:42:29.997917: info: RemoteScriptError: : 
2020-10-13T16:42:29.997929: info: RemoteScriptError: cannot import name make_biled_skin
2020-10-13T16:42:29.997941: info: RemoteScriptError: 

2020-10-13T16:42:30.216700: info: Python: INFO:_Framework.ControlSurface:216 - LOG: (APC40_MkII) Initializing...
2020-10-13T16:42:30.216760: info: RemoteScriptMessage: (APC40_MkII) Initializing...
2020-10-13T16:42:30.309413: info: Performance: Startup hook 'EnableMidiRemoteScriptManager': Running time: 1178 ms
2020-10-13T16:42:30.465345: info: IceTool: GetPackJson RPC canceled:  Reason: RPC fault., detailed error code: -100 (Not authenticated.)
2020-10-13T16:42:35.591240: info: MemoryUsage: V: 5.8 GB, R: 567.2 MB, P: 0 Bytes
2020-10-13T16:43:21.292085: info: Python: INFO:_Framework.ControlSurface:292 - LOG: (APC40_MkII) Initializing...
2020-10-13T16:43:21.292143: info: RemoteScriptMessage: (APC40_MkII) Initializing...
2020-10-13T16:43:28.781465: info: Default App: Begin SavePrefs
2020-10-13T16:43:28.788367: info: Default App: End SavePrefs
2020-10-13T16:43:28.788644: info: AMidiIO: Midi Remote Scripts: 
  MidiRemoteScript 1 [Control Surface="APC40_MkIIx" Input="None" Output="None"]
  MidiRemoteScript 2 [Control Surface="None" Input="None" Output="None"]
  MidiRemoteScript 3 [Control Surface="None" Input="None" Output="None"]
  MidiRemoteScript 4 [Control Surface="None" Input="None" Output="None"]
  MidiRemoteScript 5 [Control Surface="None" Input="None" Output="None"]
  MidiRemoteScript 6 [Control Surface="None" Input="None" Output="None"]
2020-10-13T16:43:28.788663: info: AMidiIO: Takeover Mode: None
2020-10-13T16:43:28.788870: info: AMidiIO: Midi Devices: 
  MidiInDevice [Name="UMC404HD 192k", Track=false, Sync=false, Remote=false, MIDI Clock Sync Delay=0, Sync Type="MIDI Clock", MTC Frame Rate="All", MTC Start Offset=0]
  MidiInDevice [Name="Computer Keyboard", Track=true, Sync=false, Remote=false, MIDI Clock Sync Delay=0, Sync Type="MIDI Clock", MTC Frame Rate="All", MTC Start Offset=0]
  MidiOutDevice [Name="UMC404HD 192k", Track=false, Sync=false, Remote=false, MIDI Clock Sync Delay=0, MIDI Clock Type="Song"]

**Comment by 4ndrw** [comment]
Yeah it doesn't seem to work in the current version of ableton :/
